class AppStrings {
  AppStrings(this.localeCode);

  final String localeCode;

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'appTitle': 'FreeType Whisper Studio',
      'appSubtitle':
          'A rounded desktop workspace for continuous dictation, Whisper runtime tuning, and Markdown transcripts.',
      'liveTitle': 'Live Dictation',
      'liveHint':
          'Keep listening continuously with a rolling audio window, low-latency updates, and overlap-aware text merging.',
      'start': 'Start',
      'stop': 'Stop',
      'listening': 'Listening',
      'idle': 'Idle',
      'recording': 'Recording',
      'transcribing': 'Transcribing',
      'ready': 'Ready',
      'transcript': 'Transcript',
      'notes': 'Markdown Notes',
      'segmentPreview': 'Latest Segment',
      'importTitle': 'Video To Markdown',
      'importHint':
          'Extract audio with FFmpeg, run Whisper locally, and export a clean Markdown note.',
      'importButton': 'Import Video',
      'settings': 'Runtime Settings',
      'dictationSettings': 'Dictation Settings',
      'automationSettings': 'Automation',
      'models': 'Model Library',
      'dark': 'Dark',
      'light': 'Light',
      'followSystem': 'System',
      'modelDir': 'Model directory',
      'whisperPath': 'Whisper executable',
      'whisperArgs': 'Additional Whisper args',
      'whisperArgsHint': 'Example: -ngl 99 -fa -bs 8',
      'ffmpegPath': 'FFmpeg executable',
      'selectedModel': 'Selected model',
      'download': 'Download',
      'downloadReminder':
          'This action will download a Whisper model to your device. Please confirm your network and available disk space first.',
      'missingConfig':
          'Please configure the Whisper executable and model directory first.',
      'missingImportConfig':
          'Please configure the Whisper executable, FFmpeg executable, and model directory first.',
      'missingModel': 'Please select a downloaded model file first.',
      'status': 'Status',
      'videoDone': 'Video transcription completed.',
      'modelSaved': 'Model downloaded successfully.',
      'microphonePermission':
          'Microphone access is required before live dictation can start.',
      'gpuHint':
          'Use a GPU-enabled Whisper binary here. The app calls your local executable and keeps transcription on-device.',
      'refresh': 'Refresh',
      'small': 'Compact',
      'medium': 'Balanced',
      'large': 'High accuracy',
      'all': 'All',
      'emptyTranscript': 'Your live transcript will appear here.',
      'emptyNotes': 'Generated Markdown notes will appear here.',
      'runtimeHelp':
          'Tip: point Whisper to a whisper.cpp or similar local CLI build that already supports your GPU backend.',
      'dictationLanguage': 'Dictation language',
      'latency': 'Latency profile',
      'autoDetect': 'Auto',
      'chinese': 'Chinese',
      'english': 'English',
      'fast': 'Fast',
      'steady': 'Steady',
      'precise': 'Precise',
      'liveModeHint':
          'Fast uses smaller chunks, Precise keeps a larger rolling window for smoother sentence completion.',
      'saveMarkdown': 'Save Markdown',
      'markdownSaved': 'Markdown exported successfully.',
      'noTranscriptYet': 'Generate a transcript first before exporting Markdown.',
      'copySnippet': 'Copy each confirmed snippet',
      'autoPaste': 'Auto paste into active input',
      'pasteMode': 'Paste mode',
      'pasteIncremental': 'Incremental',
      'pasteSentence': 'Sentence-final',
      'pasteWhole': 'Whole transcript',
      'pasteModeHint':
          'Incremental pastes only newly confirmed text. Sentence-final waits for punctuation or a short pause before committing. Whole transcript selects all and replaces the current field.',
      'globalHotkeys': 'Enable global hotkeys',
      'toggleHotkey': 'Toggle dictation hotkey',
      'pasteHotkey': 'Paste latest text hotkey',
      'automationHint':
          'Auto paste uses the clipboard and sends Ctrl+V. On Linux it requires xdotool.',
      'hotkeyToggleValue': 'Alt + Shift + R',
      'hotkeyPasteValue': 'Alt + Shift + V',
    },
    'zh': {
      'appTitle': 'FreeType Whisper 工作台',
      'appSubtitle': '一个圆角风格的桌面工作台，支持连续听写、Whisper 运行时调优与 Markdown 记录。',
      'liveTitle': '实时听写',
      'liveHint': '使用滚动音频窗口持续监听，并结合低延迟更新与重叠去重拼接，体验更接近 Typeless。',
      'start': '开始',
      'stop': '停止',
      'listening': '监听中',
      'idle': '空闲',
      'recording': '录音中',
      'transcribing': '转写中',
      'ready': '就绪',
      'transcript': '转写文本',
      'notes': 'Markdown 记录',
      'segmentPreview': '最新片段',
      'importTitle': '视频转 Markdown',
      'importHint': '使用 FFmpeg 提取音频后，在本地运行 Whisper，并导出为干净的 Markdown 记录。',
      'importButton': '导入视频',
      'settings': '运行设置',
      'dictationSettings': '听写设置',
      'automationSettings': '自动化',
      'models': '模型库',
      'dark': '深色',
      'light': '浅色',
      'followSystem': '跟随系统',
      'modelDir': '模型目录',
      'whisperPath': 'Whisper 可执行文件',
      'whisperArgs': 'Whisper 附加参数',
      'whisperArgsHint': '示例：-ngl 99 -fa -bs 8',
      'ffmpegPath': 'FFmpeg 可执行文件',
      'selectedModel': '当前模型',
      'download': '下载',
      'downloadReminder': '该操作会把 Whisper 模型下载到本机。请先确认网络可用，并预留足够磁盘空间。',
      'missingConfig': '请先配置 Whisper 可执行文件和模型目录。',
      'missingImportConfig': '请先配置 Whisper 可执行文件、FFmpeg 可执行文件和模型目录。',
      'missingModel': '请先选择已下载的模型文件。',
      'status': '状态',
      'videoDone': '视频转写完成。',
      'modelSaved': '模型下载完成。',
      'microphonePermission': '开始实时听写前需要先授予麦克风权限。',
      'gpuHint': '这里应选择支持 GPU 的 Whisper 可执行程序。应用只调用你本地的程序，转写全过程都留在本机。',
      'refresh': '刷新',
      'small': '轻量',
      'medium': '均衡',
      'large': '高精度',
      'all': '全部',
      'emptyTranscript': '实时转写结果会显示在这里。',
      'emptyNotes': '生成后的 Markdown 记录会显示在这里。',
      'runtimeHelp': '提示：建议将 Whisper 指向已启用 GPU 后端的 whisper.cpp 或同类本地 CLI 程序。',
      'dictationLanguage': '听写语言',
      'latency': '延迟档位',
      'autoDetect': '自动',
      'chinese': '中文',
      'english': '英文',
      'fast': '快速',
      'steady': '稳定',
      'precise': '精确',
      'liveModeHint': '快速档使用更小片段，精确档保留更长滚动窗口，更利于句子自然收尾。',
      'saveMarkdown': '保存 Markdown',
      'markdownSaved': 'Markdown 导出成功。',
      'noTranscriptYet': '请先生成转写内容，再导出 Markdown。',
      'copySnippet': '复制每次确认后的片段',
      'autoPaste': '自动粘贴到当前输入框',
      'pasteMode': '粘贴模式',
      'pasteIncremental': '增量粘贴',
      'pasteSentence': '句末提交',
      'pasteWhole': '整段粘贴',
      'pasteModeHint': '增量粘贴只插入最新确认的文本；句末提交会等到句末标点或短暂停顿后再提交；整段粘贴会先全选，再用完整转写覆盖当前输入框。',
      'globalHotkeys': '启用全局快捷键',
      'toggleHotkey': '开始或停止听写快捷键',
      'pasteHotkey': '粘贴最新文本快捷键',
      'automationHint': '自动粘贴会使用剪贴板并发送 Ctrl+V。Linux 下需要安装 xdotool。',
      'hotkeyToggleValue': 'Alt + Shift + R',
      'hotkeyPasteValue': 'Alt + Shift + V',
    },
  };

  String t(String key) => _values[localeCode]?[key] ?? _values['en']![key] ?? key;
}
